/**
 * @file goal.model.js
 * @module models/goalSchema
 * @description Model tracking the 7-category mental wellness setup pipeline using separated constants maps.
 */

const mongoose = require('mongoose');

const {
  GOAL_ENUM_VALUES,
  TIMELINE_TYPES,
  WEEKDAYS,
  DAILY_COMMITMENTS,
} = require('../constants/goal.constant');

// Define a mini-schema for tracking individual execution items
const taskItemSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true,
  },

  phase: {
    type: String, // e.g., "Week 1", "Phase 1"
    required: true,
  },

  isCompleted: {
    type: Boolean,
    default: false,
  },
});

const goalSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    // Step 1: Category lookup driven directly by our constants array
    category: {
      type: String,
      required: true,
      enum: GOAL_ENUM_VALUES,
      default: 'custom',
    },

    // Step 2: Selected template or custom title string
    title: {
      type: String,
      required: true,
      trim: true,
      maxLength: 200,
    },

    // Step 3: Setup Durations
    timelineType: {
      type: String,
      required: true,
      enum: TIMELINE_TYPES,
      default: '1_month',
    },

    startDate: {
      type: Date,
      default: Date.now,
    },

    endDate: {
      type: Date,
      default: null, // Managed programmatically via duration calculations inside the controller
    },

    // Step 4: Chosen active days
    selectedDays: {
      type: [String],
      enum: WEEKDAYS,
      required: true,
    },

    // Step 5: Daily time commitment window lengths
    dailyCommitment: {
      type: String,
      required: true,
      enum: DAILY_COMMITMENTS,
    },

    // Step 6 & 7: Description Fields & Gemini AI Data Block
    description: {
      type: String,
      trim: true,
      maxLength: 350,
      default: null,
    },

    aiGeneratedRoadmap: {
      type: String, // Holds the raw structured markdown execution roadmap generated by the Gemini API
      default: null,
    },

    tasks: [taskItemSchema],

    isAiAssistedDescription: {
      type: Boolean,
      default: false,
    },

    status: {
      type: String,
      required: true,
      enum: ['active', 'completed'],
      default: 'active',
    },

    /* -------------------------------------------------------------------------- */
    /* Tracking Progress & Gamification Indicators                                */
    /* -------------------------------------------------------------------------- */

    reminderTimes: {
      type: [String],
      default: [], // Array of times formatted as "HH:MM" for push message worker dispatch scripts
    },

    isPremiumExclusive: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

goalSchema.index({ userId: 1, status: 1 });

module.exports = mongoose.model('Goal', goalSchema);
